// COPYRIGHT Dassault Systemes 2018
//===================================================================
//
// IdentityCard.h
// Supplies the list of prerequisite components for framework CataLogFrmWrk
//
//===================================================================
//
// Usage notes:
//   For every prereq framework FW, use the syntax:
//   AddPrereqComponent ("FW", Public);
//
//===================================================================
//
//  Oct 2018  Creation: Code generated by the CAA wizard  dell
//===================================================================
// DO NOT EDIT :: THE CAA2 WIZARDS WILL ADD CODE HERE
AddPrereqComponent("ApplicationFrame",Protected);
AddPrereqComponent("DialogEngine",Protected);
AddPrereqComponent("AdvancedMathematics",Public);
AddPrereqComponent("GeometricObjects",Public);
AddPrereqComponent("GeometricOperators",Public);
AddPrereqComponent("Mathematics",Protected);
AddPrereqComponent("NewTopologicalObjects",Public);
AddPrereqComponent("System",Protected);
AddPrereqComponent("Dialog",Protected);
AddPrereqComponent("Visualization",Public);
AddPrereqComponent("TopologicalOperators",Public);
AddPrereqComponent("ObjectModelerBase",Public);
AddPrereqComponent("ObjectSpecsModeler",Public);
AddPrereqComponent("ProductStructure",Public);
AddPrereqComponent("MecModInterfaces",Public);
AddPrereqComponent("KnowledgeInterfaces",Public);
AddPrereqComponent("CATAssemblyInterfaces",Public);
AddPrereqComponent("VisualizationBase",Public);
AddPrereqComponent("MechanicalModeler",Public);
AddPrereqComponent("InteractiveInterfaces",Public);
AddPrereqComponent("Administration",Public);
AddPrereqComponent("Tessellation",Public);
AddPrereqComponent("ComponentsCatalogsInterfaces",Public);
AddPrereqComponent("InfInterfaces",Public);
AddPrereqComponent("ProductStructureUI",Public);
AddPrereqComponent("ProductStructureInterfaces",Public);
   AttachComponent("CAADraftingInterfaces.tst");
AddPrereqComponent("CATTPSInterfaces",Public);
AddPrereqComponent("DraftingInterfaces",Public);















