//===================================================================
// COPYRIGHT HUSTCAD 2018/12/04
//===================================================================
// CSaveHoops.cpp
// Header definition of class CSaveHoops
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2018/12/04 Creation: Code generated by the 3DS wizard
//===================================================================

#ifndef CSaveHoops_H
#define CSaveHoops_H

class CATIMmiPrtContainer;
class CATBody;
class CATIMmiUseGeometricalElement;
class CATRep;
#include "CATIMmiUseGeometricalElement.h"


//-----------------------------------------------------------------------

class CSaveHoops
{
public:
// Standard constructors and destructors
// -------------------------------------
CSaveHoops ();
virtual ~CSaveHoops ();

void SaveToItnevue(CATIPLMComponent *pComponent);
void SavePart(CATIPLMComponent *pComponent);
void SavePartFromGraph(CATIPLMComponent *pComponent);//从graph中获取图形数据，这部分数据是不能测量的

void SaveAsm(CATIPLMComponent *pComponent);
void SaveDrawing(CATIPLMComponent *pComponent);
void SaveStep(CATIPLMComponent *pComponent);

void ConvertRep(CATRep *pRep/*,CMapPtrToPtr &HasProcessed*/);

//static CATUnicodeString GetObjName(CATBaseUnknown *pObj);
CATUnicodeString GetComponentType(CATIPLMComponent *pComponent);

HRESULT GetMechanicalContainer (CATBaseUnknown * ipOccurrence, CATIMmiPrtContainer ** opiPrtContainer);

BOOL ConvertBodyToIntevue(CATBody *pBody,CATIMmiUseGeometricalElement_var spFeatureResultGeomElem);
void SetWeldingPointUserOption(CATBody *pBody,CATIMmiUseGeometricalElement_var spFeatureResultGeomElem);
BOOL WriteGeometrySet(CATBody *pBody,CATIMmiUseGeometricalElement_var spFeatureResultGeomElem);
//
// TODO: Add your methods for this class here.
//

BOOL GetDocAttribute(CATIPLMComponent *pComponent,CStringList &strlistName,CStringList &strlistDisplay,CStringList &strlistValue);
BOOL  GetDocAttribute(CATIPLMComponent *pComponent,CString& strPropName,CString& strTitle,CString& strValue);
int  GetDocParameter(CATIPLMComponent *pComponent,int &iPropSetsCount,CString *&strNames,CString *&strDisplayName,CStringList *&lstTitle,CStringList *&lstDisplayTitle,CStringList *&lstValue);
CString WrtitAllAttributeInXmlString(int iPropSetsCount,CString *strNames,CString *strDisplayName,CStringList *lstTitle,CStringList *lstDisplayTitle,CStringList *lstValue);

BOOL GetBodyVisiblity(CATBaseUnknown_var pElement);
private:
// Copy constructor and equal operator
// -----------------------------------
CSaveHoops (CSaveHoops &);
CSaveHoops& operator=(CSaveHoops&);

};

//-----------------------------------------------------------------------

#endif
