//===================================================================
// COPYRIGHT TY 2019/01/03
//===================================================================
// ImportIPDECmd.cpp
// Header definition of class ImportIPDECmd
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2019/01/03 Creation: Code generated by the 3DS wizard
//===================================================================
#ifndef ImportIPDECmd_H
#define ImportIPDECmd_H

#include "CATCommand.h"
class CATIPLMComponent;
class CATDlgFile;
class CATIMmiPrtContainer;
class CATBody;
class CATIMmiUseGeometricalElement;
class CATRep;
class CATDialog;
//----------------------------------------------------------------------

/**
* Describe your command here.
* <p>
* Using this prefered syntax will enable mkdoc to document your class.
* <p>
* refer to programming resources of System framework.
* (consult base class description).
*/
class ImportIPDECmd: public CATCommand
{
public:
	CATDlgFile *_dlgFile;
ImportIPDECmd();
virtual ~ImportIPDECmd();

/**
* Overload this method: when your command gains focus
* <p>
* Activates a command.
* @param iFromClient
*   The command that requests to activate the current one.
* @param iEvtDat
*   The notification sent.
*/
virtual CATStatusChangeRC Activate(
CATCommand * iFromClient,
CATNotification * iEvtDat);

/**
*  Overload this method: when your command loses focus
* <p>
* Deactivates a command.
* @param iFromClient
*   The command that takes the current active place.
* @param iEvtDat
*   The notification sent.
*/
virtual CATStatusChangeRC Desactivate(
CATCommand * iFromClient,
CATNotification * iEvtDat);

/**
*  Overload this method: when your command is canceled
* <p>
* Cancels a command.
* @param iFromClient
*   The command that takes the current active place.
* @param iEvtDat
*   The notification sent.
*/
virtual CATStatusChangeRC Cancel(
CATCommand * iFromClient,
CATNotification * iEvtDat);



void OpenOK(CATCommand           * iSendingCommand, 
	CATNotification      * iSentNotification, 
	CATCommandClientData   iUsefulData);
};

//----------------------------------------------------------------------

#endif
