//===================================================================
// COPYRIGHT HUSTCAD 2018/12/01
//===================================================================
// CatiaToIntevueAddin.cpp
// Header definition of class CatiaToIntevueAddin
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2018/12/01 Creation: Code generated by the 3DS wizard
//===================================================================
#ifdef  _WINDOWS_SOURCE
#ifdef  __CatiaToIntevueAddin
#define ExportedByCatiaToIntevueAddin     __declspec(dllexport)
#else
#define ExportedByCatiaToIntevueAddin     __declspec(dllimport)
#endif
#else
#define ExportedByCatiaToIntevueAddin
#endif
