// COPYRIGHT DASSAULT SYSTEMES 2009
#======================================================================
# Imakefile for module IPDEforCATIAAddin
#======================================================================
#  2019/01/02 Creation: Code generated by the 3DS wizard
#======================================================================
#

BUILT_OBJECT_TYPE=SHARED LIBRARY

LOCAL_LDFLAGS=-LIBPATH:"$(WSROOT)\IPDEforCATIAFrm\ExternalItf"    #.lib所在路径
SYS_LIBS =CataModule.lib           #.lib名称
LOCAL_CCFLAGS =-I"$(WSROOT)\IPDEforCATIAFrm\ExternalItf"         #头文件所在路径



#INSERTION ZONE NOT FOUND, MOVE AND APPEND THIS VARIABLE IN YOUR LINK STATEMENT
LINK_WITH = $(WIZARD_LINK_MODULES)
# DO NOT EDIT :: 3DS WIZARDS WILL ADD CODE HERE
WIZARD_LINK_MODULES = JS0FM   \
JS0GROUP CATAfrFoundation AfrInterfacesUUID \
CATDialogEngine CATMathematics CATProductStructureInterfaces \
CATPLMComponentInterfaces CATPLMComponentInterfacesUUID CATPLMIdentificationAccess \
CAT3DPhysicalRepItf CATObjectModelerBase CATMecModUseItfUUID CATMecModUseItf CATGMGeometricInterfaces \
CATMecModLiveUseItf CATGMModelInterfaces DI0PANV2 CATObjectModelerNavigator CATPLMModeler3DInterfaces \
CATDXImportExportFileServices CATDraftingUseItf PLMDictionaryNavServices KnowledgeItf \
CATBatCliMonitor PLMPSISessionInterfaces CATPLMBatch CATPLMIdentificationAccess CATPLMComponentInterfaces CATPLMIntegrationAccess CATBatchUtils \
CATVisFoundation CATVisItf
# END WIZARD EDITION ZONE
