# COPYRIGHT DASSAULT SYSTEMES 2007
#======================================================================
# Imakefile for module PdmXmlAddin.m
#======================================================================
#
#  Apr 2007  Creation: Code generated by the CAA wizard  Administrator
#======================================================================
#
# SHARED LIBRARY 
#
BUILT_OBJECT_TYPE=SHARED LIBRARY 
 
# DO NOT EDIT :: THE CAA2 WIZARDS WILL ADD CODE HERE
WIZARD_LINK_MODULES = JS0GROUP \
JS0FM  ApplicationFrame CATAfrUUID  \
DI0PANV2 CATMathematics CATDialogEngine \
 Mathematics CATMathStream CATCGMGeoMath AdvancedMathematics\
            CATGeometricObjects CATGeometricOperators\
            CATTopologicalOperators CATTopologicalObjects CATTessellation\
			CATObjectSpecsModeler  KnowledgeItf\
            CATObjectModelerBase \
            CATProductStructure1 \
            CATAssemblyInterfaces\         
			CATMecModInterfaces\
			CATVisualization CATViz\		
   		CATMechanicalModeler\
			CATInteractiveInterfaces\
			WFTOCACD\						
				CATInfInterfaces\
			CATDraftingInterfaces\
			CATProductStructureInterfaces\
		JS0FM DI0PANV2 CATMathematics CATDialogEngine CATCclInterfaces 
		

# END WIZARD EDITION ZONE

LINK_WITH = $(WIZARD_LINK_MODULES)

# System dependant variables
#
OS = AIX
#
OS = HP-UX
#
OS = IRIX
#
OS = SunOS
#
OS = Windows_NT
