//===================================================================
// COPYRIGHT HUSTCAD 2018/12/14
//===================================================================
// CDlgSetOptionCmd.cpp
// Header definition of class CDlgSetOptionCmd
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2018/12/14 Creation: Code generated by the 3DS wizard
//===================================================================

#ifndef CDlgSetOptionCmd_H
#define CDlgSetOptionCmd_H

//#include "CatiaToIntevueAddin.h"
#include "CATDlgDialog.h"

//-----------------------------------------------------------------------

class  CDlgSetOptionCmd: public CATDlgDialog
{
public:

	//
	// In the Cnext/resources/msgcatalog you have :
	//     CAAAfrBoundingElementCmd.CATNls 
	//    
	DeclareResource(CDlgSetOptionCmd, CATDlgDialog); //定义资源文件所在的位置
// Standard constructors and destructors
// -------------------------------------
CDlgSetOptionCmd ();
virtual ~CDlgSetOptionCmd ();

//
// TODO: Add your methods for this class here.
//

private:
	//对话框中的对象
	CATDlgLabel *_ChordLabel;
	CATDlgEditor *_ChordEditor;
	CATDlgCheckButton *_OuputStep;
	CATDlgCheckButton *_OutputPmi;
	CATDlgCheckButton *_FromGraph;//从graph中输出信息

	void ClickOK(CATCommand           * iSendingCommand, 
		CATNotification      * iSentNotification, 
		CATCommandClientData   iUsefulData);
	void ClickCancel(CATCommand           * iSendingCommand, 
		CATNotification      * iSentNotification, 
		CATCommandClientData   iUsefulData);

	

// Copy constructor and equal operator
// -----------------------------------
CDlgSetOptionCmd (CDlgSetOptionCmd &);
CDlgSetOptionCmd& operator=(CDlgSetOptionCmd&);

};

//-----------------------------------------------------------------------

#endif
