//===================================================================
// COPYRIGHT HUSTCAD 2018/12/14
//===================================================================
// CTestCmd.cpp
// Header definition of class CTestCmd
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2018/12/14 Creation: Code generated by the 3DS wizard
//===================================================================

#ifndef CTestCmd_H
#define CTestCmd_H

//#include "CatiaToIntevueAddin.h"
#include "CATDlgDialog.h"

//-----------------------------------------------------------------------
//这个对话框主要用来进行测试用的；
class  CTestCmd: public CATDlgDialog
{
public:
// Standard constructors and destructors
// -------------------------------------
CTestCmd ();
virtual ~CTestCmd ();

//
// TODO: Add your methods for this class here.
//


void ClickOK(CATCommand           * iSendingCommand, 
	CATNotification      * iSentNotification, 
	CATCommandClientData   iUsefulData);

void ClickOputStep(CATCommand           * iSendingCommand, 
	CATNotification      * iSentNotification, 
	CATCommandClientData   iUsefulData);


private:
// Copy constructor and equal operator
// -----------------------------------
CTestCmd (CTestCmd &);
CTestCmd& operator=(CTestCmd&);

CATDlgPushButton *_OutputStep;

};

//-----------------------------------------------------------------------

#endif
