//===================================================================
// COPYRIGHT TY 2019/01/02
//===================================================================
// IPDEforCATIAAddin.cpp
// Header definition of class IPDEforCATIAAddin
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2019/01/02 Creation: Code generated by the 3DS wizard
//===================================================================

#ifndef IPDEforCATIAAddin_H
#define IPDEforCATIAAddin_H

#include "CATBaseUnknown.h"

//-----------------------------------------------------------------------
class CATCmdContainer;
class IPDEforCATIAAddin: public CATBaseUnknown
{
	CATDeclareClass;
public:
// Standard constructors and destructors
// -------------------------------------
IPDEforCATIAAddin ();
virtual ~IPDEforCATIAAddin ();

//
// TODO: Add your methods for this class here.
//
void CreateCommands();
CATCmdContainer * CreateToolbars();
private:
// Copy constructor and equal operator
// -----------------------------------
IPDEforCATIAAddin (IPDEforCATIAAddin &);
IPDEforCATIAAddin& operator=(IPDEforCATIAAddin&);

};

//-----------------------------------------------------------------------

#endif
