set A3DT=e:\Acis\
set ADL_DB2INSTANCE=DB2
set ADL_DFLT_RULES_LIB=ADLCMCNextArchiRules
set ADL_DIFF_LOCAL=N
set ADL_DIFF_PATH=N/A
set ADL_MERGER="C:\Program Files (x86)\Dassault Systemes\B19\intel_a\code\command\ADLMerger2.bat"
set ADL_NLS_LANG=AMERICAN_AMERICA.WE8ISO8859P1
set ADL_ORA_TNS_ADMIN=NA
set ADL_PATH=C:\Program Files (x86)\Dassault Systemes\B19\intel_a
set ADL_SITE_NAME=V5R19_B19
set ADL_TMP=C:\TEMP
set ADL_USER_PATH=C:\Program Files (x86)\Dassault Systemes\B19\intel_a\code\command
set ALLUSERSPROFILE=C:\ProgramData
set APPDATA=C:\Users\Ymc\AppData\Roaming
set BLD_HOST_OS=win_b64
set CommonProgramFiles=C:\Program Files (x86)\Common Files
set CommonProgramFiles(x86)=C:\Program Files (x86)\Common Files
set CommonProgramW6432=C:\Program Files\Common Files
set COMPUTERNAME=YMC-PC
set ComSpec=C:\Windows\system32\cmd.exe
set CorbaCppBuildROOT_PATH=\\ds\dsy\iona\Orbix3.3\win_b64
set CorbaCppROOT_PATH=\\ds\dsy\iona\Orbix3.3\win_b64
set CorbaJavaROOT_PATH=\\ds\dsy\iona\Orbix3.3\win_b64
set CSCSkipTestOfMapFileValidity=1
set DSarMakerROOT_PATH=C:\PROGRA~2\DASSAU~1\B19\CATWebDSarMaker
set DXSDK_DIR=C:\Program Files (x86)\Microsoft DirectX SDK (June 2010)\
set FP_NO_HOST_CHECK=NO
set HOMEDRIVE=C:
set HOMEPATH=\Users\Ymc
set HOOPS1919_DIR=E:\osg\HOOPS-1919
set INCLUDE=C:\PROGRA~2\DASSAU~1\B19\intel_a\.\tools\include\win_b64;C:\PROGRA~2\DASSAU~1\B19\intel_a\.\tools\include;D:\vs2005\VC\include;D:\vs2005\VC\atlmfc\include;D:\vs2005\VC\PlatformSDK\include
set JAVA_HOME=C:\Program Files\Java\jdk1.7.0_80
set JLMDeployROOT_PATH=C:\PROGRA~2\DASSAU~1\B19\intel_a\jlm\jlmdeploy65
set LIB=C:\Program Files\Reference Assemblies\Microsoft\Framework\v3.0;D:\vs2005\VC\lib\amd64;D:\vs2005\VC\atlmfc\lib\amd64;D:\vs2005\VC\PlatformSDK\lib\amd64
set LOCALAPPDATA=C:\Users\Ymc\AppData\Local
set LOGONSERVER=\\YMC-PC
set mkcsClientMode=1
set mkcsOS_Buildtime=intel_a
set mkcsOS_NAME=Windows_NT
set mkcsOS_Runtime=intel_a
set mkcsROOT_PATH=C:\PROGRA~2\DASSAU~1\B19\intel_a
set mkcsSHLIB_NAME=PATH
set mkcsSHLIB_PATH=C:\PROGRA~2\DASSAU~1\B19\intel_a\code\bin
set MkmkADDON_LEVEL=MK_ORBIXCPP33 MK_ORBIXJAVA33 MK_MSCVER=1400
set MkmkADDON_LIB=C:\Program Files\Reference Assemblies\Microsoft\Framework\v3.0;C:\Windows\Microsoft.NET\Framework64\v2.0.50727
set MkmkADDON_PATH=C:\Windows\Microsoft.NET\Framework64\v2.0.50727
set MkmkASPNET20Internal=yes
set MkmkBAD_MINITFLEVEL=4
set mkmkbuild=21901
set MkmkDictionary_PATH=C:\PROGRA~2\DASSAU~1\B19\intel_a\.\code\dictionary
set MkmkIC_PATH=C:\PROGRA~2\DASSAU~1\B19\intel_a\.\code\productIC
set MkmkIF60=yes
set MkmkIF60Internal=yes
set MkmkIF90Internal=yes
set MkmkINSTALL_PATH=C:\PROGRA~2\DASSAU~1\B19
set MkmkMsgCatalog_PATH=C:\PROGRA~2\DASSAU~1\B19\intel_a\.\resources\msgcatalog
set MkmkMSNET30DIR=C:\Program Files\Reference Assemblies\Microsoft\Framework\v3.0
set MkmkMSVCADDON_INCLUDE_80=D:\vs2005\VC\include;D:\vs2005\VC\atlmfc\include;D:\vs2005\VC\PlatformSDK\include
set MkmkMSVCADDON_LIB_80=D:\vs2005\VC\lib\amd64;D:\vs2005\VC\atlmfc\lib\amd64;D:\vs2005\VC\PlatformSDK\lib\amd64
set MkmkMSVCADDON_PATH_80=D:\vs2005\VC\bin\amd64
set MkmkMSVCDIR=D:\vs2005\VC
set MkmkMSVCDIR_80=D:\vs2005\VC
set MkmkMSVCSHARPDIR=C:\Windows\Microsoft.NET\Framework64\v2.0.50727
set MkmkMSVJSHARPDIR=C:\Windows\Microsoft.NET\Framework64\v2.0.50727
set MkmkMSVSADDON_PATH_80=D:\vs2005\Common7\Tools\Bin;D:\vs2005\Common7\IDE
set MkmkMSVSBINDIR=D:\vs2005\Common7\IDE
set MkmkOrbixCpp33=yes
set MkmkOrbixCpp33Internal=yes
set MkmkOrbixJava33=yes
set MkmkOrbixJava33Internal=yes
set MkmkOS_BitMode=64
set MkmkOS_Buildtime=win_b64
set MkmkOS_DOC=DOC
set MkmkOS_NAME=Windows_NT
set MkmkOS_Runtime=intel_a
set MkmkOS_Type=Windows
set MkmkOS_VAR=win_b64
set MkmkReffiles_PATH=C:\PROGRA~2\DASSAU~1\B19\intel_a\.\reffiles
set MkmkRMSSDK_PATH=C:\PROGRA~2\DASSAU~1\B19\intel_a\.\rms\rmssdksp2
set MkmkROOT_PATH=C:\PROGRA~2\DASSAU~1\B19\intel_a
set MkmkSHLIB_NAME=Path
set MkmkSHLIB_PATH=C:\PROGRA~2\DASSAU~1\B19\intel_a\code\bin
set mkmkvers=mkmk Version 2.19.1
set MkmkVERSIONINFO=NO
set MkmkVS60=yes
set MkmkVS60Internal=yes
set MkmkVS80Internal=yes
set MkmkXMLMANIFEST=NO
set Mkmk_Modifier=554
set Mkmk_Modifier_BAD=16
set MKMK_USEPRECOMPIL=yes
set MkodtOS_Runtime=win_b64
set MK_DEVNULL=NUL
set MK_SEPARATOR=\;
set MK_TEMPDIR=C:\temp
set MOZ_PLUGIN_PATH=D:\Foxit Reader\plugins\
set NO_LOCAL_DEFINITION_FOR_IID=yes
set NTsetenvPath=C:\PROGRA~2\DASSAU~1\B19\intel_a\code\command\
set NUMBER_OF_PROCESSORS=4
set OS=Windows_NT
set OSG_FILE_PATH=D:\OSG\data
set OSG_NOTIFY_LEVEL=WARN
set OSMFEATROOT_PATH="\\atlas\tools\osmfeat\osmfeat\"
set PATH=D:\vs2005\VC\bin\amd64;C:\Program Files\Reference Assemblies\Microsoft\Framework\v3.0;C:\Windows\Microsoft.NET\Framework64\v2.0.50727;D:\vs2005\Common7\Tools\Bin;D:\vs2005\Common7\IDE;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.0\;D:\OSG\OpenSceneGraph-3.0.0\bin;C:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\;C:\Program Files\Microsoft SQL Server\100\Tools\Binn\;C:\Program Files\Microsoft SQL Server\100\DTS\Binn\;C:\Program Files\Microsoft\Web Platform Installer\;C:\Program Files (x86)\Microsoft ASP.NET\ASP.NET Web Pages\v1.0\;D:\NginxServer\RunHiddenConsole;C:\Program Files (x86)\AMD\ATI.ACE\Core-Static;D:\Git\cmd;D:\nodejs\;C:\Program Files\Java\jdk1.7.0_80\bin;C:\Users\Ymc\AppData\Local\Programs\Python\Python37\Scripts\;C:\Users\Ymc\AppData\Local\Programs\Python\Python37\;D:\vscode\Microsoft VS Code\bin;d:\Program Files (x86)\IDM Computer Solutions\UltraEdit-32;C:\Users\Ymc\AppData\Roaming\npm;C:\Program Files (x86)\Dassault Systemes\B19\intel_a\TCK\command;C:\PROGRA~2\DASSAU~1\B19\intel_a\code\command;C:\PROGRA~2\DASSAU~1\B19\intel_a\code\command;C:\Program Files (x86)\Dassault Systemes\B19\intel_a\code\command
set PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
set Path_bak=C:\Users\Ymc\AppData\Roaming\npm;D:\vscode\Microsoft VS Code\bin
set PROCESSOR_ARCHITECTURE=AMD64
set PROCESSOR_ARCHITEW6432=AMD64
set PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 42 Stepping 7, GenuineIntel
set PROCESSOR_LEVEL=6
set PROCESSOR_REVISION=2a07
set ProgramData=C:\ProgramData
set ProgramFiles=C:\Program Files (x86)
set ProgramFiles(x86)=C:\Program Files (x86)
set ProgramW6432=C:\Program Files
set PROMPT=$P$G
set PSModulePath=C:\Windows\system32\WindowsPowerShell\v1.0\Modules\
set PUBLIC=C:\Users\Public
set P_SCHEMA=D:\Inte3D×°Åä\lib3dx\intel_a\code\bin\schemas\
set RADECATSettingPath=C:\Users\Ymc\AppData\Roaming\DassaultSystemes\RADE
set RELEASEMANAGER_PATH=C:\PROGRA~2\DASSAU~1\B19\intel_a
set rtcode=0
set SESSIONNAME=Console
set SPATIALDIR=D:\Spatial
set SystemDrive=C:
set SystemRoot=C:\Windows
set TCKHelp=-
set TCKOS_Runtime=intel_a
set TCK_DATE=2019/01/11-13:43:35
set TCK_ID=V5R19_B19
set TCK_INSTALL_PATH=C:\Program Files (x86)\Dassault Systemes\B19
set TCK_LOCAL_INFO=C:\Program Files (x86)
set TCK_NAME=V5R19_B19
set TCK_NO_SERVER=true
set TCK_ROOT_PATH=C:\Program Files (x86)\Dassault Systemes\B19\intel_a
set TCK_TMP_FILE=C:\Users\Ymc\AppData\Local\Temp\tckexec__Ymc_7776.bat
set TEMP=C:\Users\Ymc\AppData\Local\Temp
set TMP=C:\Users\Ymc\AppData\Local\Temp
set TMPFILE=\adl_unset_17085.bat
set USERDOMAIN=Ymc-PC
set USERNAME=Ymc
set USERPROFILE=C:\Users\Ymc
set VBTtmp=C:\Users\Ymc\AppData\Local\Temp
set VS100COMNTOOLS=D:\vs2010\Common7\Tools\
set VS110COMNTOOLS=C:\Program Files (x86)\Microsoft Visual Studio 11.0\Common7\Tools\
set VS120COMNTOOLS=D:\vs2013\Common7\Tools\
set VS80COMNTOOLS=D:\vs2005\Common7\Tools\
set WecVersionForRosebud.1918=2
set windir=C:\Windows
set windows_tracing_flags=3
set windows_tracing_logfile=C:\BVTBin\Tests\installpackage\csilogfile.log
set _tck_exec=OK
set __COMPAT_LAYER=ElevateCreateProcess
