// COPYRIGHT DASSAULT SYSTEMES 2009
#======================================================================
# Imakefile for module CatiaToIntevueAddin
#======================================================================
#  2018/12/01 Creation: Code generated by the 3DS wizard
#======================================================================
#

BUILT_OBJECT_TYPE=SHARED LIBRARY

#INSERTION ZONE NOT FOUND, MOVE AND APPEND THIS VARIABLE IN YOUR LINK STATEMENT
LINK_WITH = $(WIZARD_LINK_MODULES)
# DO NOT EDIT :: 3DS WIZARDS WILL ADD CODE HERE
WIZARD_LINK_MODULES = JS0FM   \
JS0GROUP CATAfrFoundation AfrInterfacesUUID \
CATDialogEngine CATMathematics CATProductStructureInterfaces \
CATPLMComponentInterfaces CATPLMComponentInterfacesUUID CATPLMIdentificationAccess \
CAT3DPhysicalRepItf CATObjectModelerBase CATMecModUseItfUUID CATMecModUseItf CATGMGeometricInterfaces \
CATMecModLiveUseItf CATGMModelInterfaces DI0PANV2 CATObjectModelerNavigator CATPLMModeler3DInterfaces \
CATDXImportExportFileServices CATDraftingUseItf PLMDictionaryNavServices KnowledgeItf \
CATVisFoundation CATVisItf


# END WIZARD EDITION ZONE
