//===================================================================
// COPYRIGHT TY 2019/01/02
//===================================================================
// IPDEforCATIAAddin.cpp
// Header definition of class IPDEforCATIAAddin
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2019/01/02 Creation: Code generated by the 3DS wizard
//===================================================================
#ifdef  _WINDOWS_SOURCE
#ifdef  __IPDEforCATIAAddin
#define ExportedByIPDEforCATIAAddin     __declspec(dllexport)
#else
#define ExportedByIPDEforCATIAAddin     __declspec(dllimport)
#endif
#else
#define ExportedByIPDEforCATIAAddin
#endif
