E:\projects10\IPDEforCATIA\.\IPDEforCATIAFrm\IPDEforCATIAAddin.m\src
E:\projects10\IPDEforCATIA\.\IPDEforCATIAFrm\IPDEforCATIAAddin.m\LocalInterfaces
E:\projects10\IPDEforCATIA\.\IPDEforCATIAFrm\IPDEforCATIAAddin.m\LocalGenerated\win_b64
E:\projects10\IPDEforCATIA\.\IPDEforCATIAFrm\PrivateInterfaces
E:\projects10\IPDEforCATIA\.\IPDEforCATIAFrm\PublicInterfaces
C:\Program Files\Dassault Systemes\B216\.\AfrFoundation\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B216\.\AfrFoundation\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B216\.\AfrFoundation\PublicInterfaces
C:\Program Files\Dassault Systemes\B216\.\AfrInterfaces\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B216\.\AfrInterfaces\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B216\.\AfrInterfaces\PublicInterfaces
C:\Program Files\Dassault Systemes\B216\.\AfrInterfaces\PublicGenerated\win_b64
C:\Program Files\Dassault Systemes\B216\.\AfrStandard\PublicInterfaces
C:\Program Files\Dassault Systemes\B216\.\AfrStandard\PublicGenerated\win_b64
C:\Program Files\Dassault Systemes\B216\.\BSFBuildtimeData\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B216\.\BSFBuildtimeData\PublicInterfaces
C:\Program Files\Dassault Systemes\B216\.\BatchInfrastructure\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B216\.\BatchInfrastructure\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B216\.\BatchInfrastructure\PublicInterfaces
C:\Program Files\Dassault Systemes\B216\.\BatchInfrastructure\PublicGenerated\win_b64
C:\Program Files\Dassault Systemes\B216\.\CAT3DPhysicalRepInterfaces\PublicInterfaces
C:\Program Files\Dassault Systemes\B216\.\CATDXImportExportFile\PublicInterfaces
C:\Program Files\Dassault Systemes\B216\.\CATMecModLiveUseItf\PublicInterfaces
C:\Program Files\Dassault Systemes\B216\.\CATMecModUseItf\PublicInterfaces
C:\Program Files\Dassault Systemes\B216\.\CATMecModUseItf\PublicGenerated\win_b64
C:\Program Files\Dassault Systemes\B216\.\CATPLMComponentInterfaces\PublicInterfaces
C:\Program Files\Dassault Systemes\B216\.\CATPLMComponentInterfaces\PublicGenerated\win_b64
C:\Program Files\Dassault Systemes\B216\.\CATPLMIdentificationAccess\PrivateInterfaces
C:\Program Files\Dassault Systemes\B216\.\CATPLMIdentificationAccess\PrivateGenerated\win_b64
C:\Program Files\Dassault Systemes\B216\.\CATPLMIdentificationAccess\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B216\.\CATPLMIdentificationAccess\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B216\.\CATPLMIdentificationAccess\PublicInterfaces
C:\Program Files\Dassault Systemes\B216\.\CATPLMIntegrationAccess\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B216\.\CATPLMIntegrationAccess\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B216\.\CATPLMIntegrationAccess\PublicInterfaces
C:\Program Files\Dassault Systemes\B216\.\Dialog\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B216\.\Dialog\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B216\.\Dialog\PublicInterfaces
C:\Program Files\Dassault Systemes\B216\.\DialogEngine\PublicInterfaces
C:\Program Files\Dassault Systemes\B216\.\DraftingUseItf\PublicInterfaces
C:\Program Files\Dassault Systemes\B216\.\DraftingUseItf\PublicGenerated\win_b64
C:\Program Files\Dassault Systemes\B216\.\GMModelInterfaces\PublicInterfaces
C:\Program Files\Dassault Systemes\B216\.\GeometricObjects\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B216\.\GeometricObjects\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B216\.\GeometricObjects\PublicInterfaces
C:\Program Files\Dassault Systemes\B216\.\GeometricObjects\PublicGenerated\win_b64
C:\Program Files\Dassault Systemes\B216\.\InteractiveInterfaces\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B216\.\InteractiveInterfaces\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B216\.\InteractiveInterfaces\PublicInterfaces
C:\Program Files\Dassault Systemes\B216\.\InteractiveInterfaces\PublicGenerated\win_b64
C:\Program Files\Dassault Systemes\B216\.\KnowledgeIDLItf\PublicInterfaces
C:\Program Files\Dassault Systemes\B216\.\KnowledgeIDLItf\PublicGenerated\win_b64
C:\Program Files\Dassault Systemes\B216\.\KnowledgeInterfaces\PrivateInterfaces
C:\Program Files\Dassault Systemes\B216\.\KnowledgeInterfaces\PrivateGenerated\win_b64
C:\Program Files\Dassault Systemes\B216\.\KnowledgeInterfaces\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B216\.\KnowledgeInterfaces\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B216\.\KnowledgeInterfaces\PublicInterfaces
C:\Program Files\Dassault Systemes\B216\.\KnowledgeInterfaces\PublicGenerated\win_b64
C:\Program Files\Dassault Systemes\B216\.\Mathematics\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B216\.\Mathematics\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B216\.\Mathematics\PublicInterfaces
C:\Program Files\Dassault Systemes\B216\.\ObjectModelerBase\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B216\.\ObjectModelerBase\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B216\.\ObjectModelerBase\PublicInterfaces
C:\Program Files\Dassault Systemes\B216\.\ObjectModelerBase\PublicGenerated\win_b64
C:\Program Files\Dassault Systemes\B216\.\ObjectModelerNavigator\PublicInterfaces
C:\Program Files\Dassault Systemes\B216\.\ObjectModelerNavigator\PublicGenerated\win_b64
C:\Program Files\Dassault Systemes\B216\.\ObjectModelerSystem\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B216\.\ObjectModelerSystem\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B216\.\ObjectModelerSystem\PublicInterfaces
C:\Program Files\Dassault Systemes\B216\.\ObjectModelerSystem\PublicGenerated\win_b64
C:\Program Files\Dassault Systemes\B216\.\PLMBatchDataAccessInterfaces\PublicInterfaces
C:\Program Files\Dassault Systemes\B216\.\PLMDictionaryNavServices\PublicInterfaces
C:\Program Files\Dassault Systemes\B216\.\PLMModelerBaseInterfaces\PublicInterfaces
C:\Program Files\Dassault Systemes\B216\.\PLMSessionInterfaces\PublicInterfaces
C:\Program Files\Dassault Systemes\B216\.\ProductStructureInterfaces\PublicInterfaces
C:\Program Files\Dassault Systemes\B216\.\ProductStructureInterfaces\PublicGenerated\win_b64
C:\Program Files\Dassault Systemes\B216\.\SpecialAPI\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B216\.\SpecialAPI\PublicInterfaces
C:\Program Files\Dassault Systemes\B216\.\SpecialAPI\PublicGenerated\win_b64
C:\Program Files\Dassault Systemes\B216\.\System\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B216\.\System\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B216\.\System\PublicInterfaces
C:\Program Files\Dassault Systemes\B216\.\System\PublicGenerated\win_b64
C:\Program Files\Dassault Systemes\B216\.\SystemTS\PrivateInterfaces
C:\Program Files\Dassault Systemes\B216\.\SystemTS\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B216\.\SystemTS\PublicInterfaces
C:\Program Files\Dassault Systemes\B216\.\VisualizationController\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B216\.\VisualizationController\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B216\.\VisualizationController\PublicInterfaces
C:\Program Files\Dassault Systemes\B216\.\VisualizationController\PublicGenerated\win_b64
C:\Program Files\Dassault Systemes\B216\.\VisualizationFoundation\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B216\.\VisualizationFoundation\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B216\.\VisualizationFoundation\PublicInterfaces
C:\Program Files\Dassault Systemes\B216\.\VisualizationInterfaces\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B216\.\VisualizationInterfaces\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B216\.\VisualizationInterfaces\PublicInterfaces
C:\Program Files\Dassault Systemes\B216\.\VisualizationInterfaces\PublicGenerated\win_b64
C:\Program Files\Dassault Systemes\B216\.\AdvancedMathematics\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B216\.\AdvancedMathematics\PublicInterfaces
C:\Program Files\Dassault Systemes\B216\.\AfrComponentsModel\PrivateInterfaces
C:\Program Files\Dassault Systemes\B216\.\AfrComponentsModel\PrivateGenerated\win_b64
C:\Program Files\Dassault Systemes\B216\.\AfrComponentsModel\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B216\.\AfrComponentsModel\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B216\.\CATDibModelerUseItf\PublicInterfaces
C:\Program Files\Dassault Systemes\B216\.\CATDibModelerUseItf\PublicGenerated\win_b64
C:\Program Files\Dassault Systemes\B216\.\CATMathStream\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B216\.\CATMathStream\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B216\.\CATMathStream\PublicInterfaces
C:\Program Files\Dassault Systemes\B216\.\CATPLMIntegrationAccessItf\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B216\.\CATStyleProcessor\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B216\.\CATStyleProcessor\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B216\.\CATVirtualVaultSystem\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B216\.\CATVirtualVaultSystem\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B216\.\Communications\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B216\.\Communications\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B216\.\Communications\PublicInterfaces
C:\Program Files\Dassault Systemes\B216\.\DataCommonProtocolUse\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B216\.\DataCommonProtocolUse\PublicInterfaces
C:\Program Files\Dassault Systemes\B216\.\DataCommonProtocolUse\PublicGenerated\win_b64
C:\Program Files\Dassault Systemes\B216\.\IVInterfaces\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B216\.\IVInterfaces\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B216\.\InfInterfaces\PublicInterfaces
C:\Program Files\Dassault Systemes\B216\.\InfInterfaces\PublicGenerated\win_b64
C:\Program Files\Dassault Systemes\B216\.\InfOSIDLItf\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B216\.\InfOSIDLItf\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B216\.\InfOSIDLItf\PublicInterfaces
C:\Program Files\Dassault Systemes\B216\.\InfOSIDLItf\PublicGenerated\win_b64
C:\Program Files\Dassault Systemes\B216\.\IntrospectionInfrastructure\PrivateInterfaces
C:\Program Files\Dassault Systemes\B216\.\IntrospectionInfrastructure\PrivateGenerated\win_b64
C:\Program Files\Dassault Systemes\B216\.\IntrospectionInfrastructure\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B216\.\IntrospectionInfrastructure\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B216\.\MultimediaPixelImage\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B216\.\MultimediaPixelImage\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B216\.\MultimediaPixelImage\PublicInterfaces
C:\Program Files\Dassault Systemes\B216\.\ObjectModelerCollection\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B216\.\ObjectModelerEngines\PrivateInterfaces
C:\Program Files\Dassault Systemes\B216\.\ObjectModelerEngines\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B216\.\ObjectModelerEngines\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B216\.\ObjectModelerInterfaces\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B216\.\ObjectModelerInterfaces\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B216\.\UIVCoreTools\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B216\.\VisualizationCore\PrivateInterfaces
C:\Program Files\Dassault Systemes\B216\.\VisualizationCore\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B216\.\VisualizationCore\PublicInterfaces
C:\Program Files\Dassault Systemes\B216\.\VisualizationSceneGraph\PrivateInterfaces
C:\Program Files\Dassault Systemes\B216\.\VisualizationSceneGraph\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B216\.\XMLParserItf\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B216\.\XMLParserItf\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B216\.\XMLParserItf\PublicInterfaces
C:\Program Files\Dassault Systemes\B216\.\XMLParserItf\PublicGenerated\win_b64
