//===================================================================
// COPYRIGHT HUSTCAD 2018/12/01
//===================================================================
// CCatiaToIntevueAddin.cpp
// Header definition of class CCatiaToIntevueAddin
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2018/12/01 Creation: Code generated by the 3DS wizard
//===================================================================

#include "CCatiaToIntevueAddin.h"

#include "CATAfrCommandHeader.h"
#include "CATCreateWorkshop.h"

class CATCmdContainer;

// To declare that the class is a DataExtension of (late type) CAAAfrGeoClippingAddin
//
//CATImplementClass(CCatiaToIntevueAddin, DataExtension, 
//	CATBaseUnknown, CCatiaToIntevueAddin);
//CATImplementClass(CCatiaToIntevueAddin,TransientExtension,CATNull,CATBaseUnknown);

//CATImplementClass(CCatiaToIntevueAddin, DataExtension, 
//	CATBaseUnknown, CCatiaToIntevueAddin);

CATImplementClass(CCatiaToIntevueAddin,
	Implementation,
	CATBaseUnknown,
	CATnull );

//定义并实现接口，这个接口应该是catia在调用dll的时候会启动这个东东
#include "TIE_CATIAfrGeneralWksAddin.h"
TIE_CATIAfrGeneralWksAddin(CCatiaToIntevueAddin);



//-----------------------------------------------------------------------------
// CCatiaToIntevueAddin : constructor
//-----------------------------------------------------------------------------
CCatiaToIntevueAddin::CCatiaToIntevueAddin():CATBaseUnknown()
{
//
//TODO: Add the constructor code here
//
}

//-----------------------------------------------------------------------------
// CCatiaToIntevueAddin : destructor
//-----------------------------------------------------------------------------

CCatiaToIntevueAddin::~CCatiaToIntevueAddin()
{
//
// TODO: Place code here.
//
}

//用于创建commandheader，所有的command都必须要有一个commandheader
void CCatiaToIntevueAddin::CreateCommands()
{
	MessageBox(NULL,_T("Create Commmands "),_T("CatiaToIntevue"),MB_OK);
	//创建一个savetointevuecommandHeader

	CATBaseUnknown *pUnknown=	CATAfrCommandHeader::CATCreateCommandHeader(
		"SaveToIntevueHdr",  //命令的id，自己定义
		"CatiaToIntevueAddin",  //dll的名称
		"CSaveToIntevueCmd", //command的类型 
		(void *)NULL, //传给command的参数
		"CatiaToIntevueHeader",// command对应的资源文件名称
		CATFrmAvailable);
	if(pUnknown==NULL)
		MessageBox(NULL,_T("Create Commmand error! "),_T("CatiaToIntevue"),MB_OK);
     
	CATAfrCommandHeader::CATCreateCommandHeader(
		"SetIntevueOptionHdr",  //命令的id，自己定义
		"CatiaToIntevueAddin",  //dll的名称
		"CDlgSetOptionCmd", //command的类型 
		(void *)NULL, //传给command的参数
		"CatiaToIntevueHeader",// command对应的资源文件名称
		CATFrmAvailable);

	CATAfrCommandHeader::CATCreateCommandHeader(
		"TestHdr",  //命令的id，自己定义
		"CatiaToIntevueAddin",  //dll的名称
		"CTestCmd", //command的类型 
		(void *)NULL, //传给command的参数
		"CatiaToIntevueHeader",// command对应的资源文件名称
		CATFrmAvailable);

	
}

//在acitve bar中创建相应的button
CATCmdContainer * CCatiaToIntevueAddin::CreateToolbars()
{
	NewAccess(CATCmdContainer, pCataToIntevueTlb, CatiaToIntevueTlb);

	NewAccess(CATCmdContainer, pFixedSection, AfrActionBarFixedSection);
	AddAccessChild(pFixedSection, pCataToIntevueTlb);

	NewAccess(CATCmdStarter, pSaveToIntevueStr, SaveToIntevueStr);
	SetAccessCommand(pSaveToIntevueStr, "SaveToIntevueHdr");
	SetAccessChild(pCataToIntevueTlb, pSaveToIntevueStr);

	NewAccess(CATCmdStarter, pSetIntevueOptionStr, SetIntevueOptionStr);
	SetAccessCommand(pSetIntevueOptionStr, "SetIntevueOptionHdr");
	SetAccessNext(pSaveToIntevueStr, pSetIntevueOptionStr);

	NewAccess(CATCmdStarter, pTestStr, TestStr);
	SetAccessCommand(pTestStr, "TestHdr");
	SetAccessNext(pSetIntevueOptionStr, pTestStr);


	CATBaseUnknown * pCommand;
	pCommand=CATAfrCommandHeader::CATGetCommandHeader("SaveToIntevueHdr");
	if(pCommand==NULL)
		MessageBox(NULL,_T("Get Command Head error! "),_T("CatiaToIntevue"),MB_OK);
	return pFixedSection;
}





