//===================================================================
// COPYRIGHT HUSTCAD 2018/12/14
//===================================================================
// CDlgSetOptionCmd.cpp
// Header definition of class CDlgSetOptionCmd
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2018/12/14 Creation: Code generated by the 3DS wizard
//===================================================================

#include "CATApplicationFrame.h"
#include "CATDlgDialog.h"
#include "CATDlgLabel.h"
#include "CATDlgEditor.h"
#include "CATDlgCheckButton.h"

#include "CDlgSetOptionCmd.h"
#include "CATCreateExternalObject.h" 


#include "CComFun.h"



CATCreateClass(CDlgSetOptionCmd);
//-----------------------------------------------------------------------------
// CDlgSetOptionCmd : constructor
//-----------------------------------------------------------------------------
CDlgSetOptionCmd::CDlgSetOptionCmd() :
CATDlgDialog(CATApplicationFrame::GetFrame()->GetMainWindow(),
	"CDlgSetOptionCmdId", 
	CATDlgGridLayout | CATDlgWndBtnOKCancel )
{
	//创建对象
	_ChordLabel=new CATDlgLabel(this,"ChordLabelId");	
	_ChordEditor=new CATDlgEditor(this,"ChorEditorId",CATDlgEdtFloat);
	_OuputStep=new CATDlgCheckButton(this,"OutputStepId");
	_OutputPmi=new CATDlgCheckButton(this,"OutputPmiId");
	_FromGraph=new CATDlgCheckButton(this,"FromGraphId");

	_ChordEditor->SetFloatValue(CComFun::gfChord);
	if(CComFun::gbOutputStep)
	{
		_OuputStep->SetState(CATDlgCheck);
	}
	else
	{
		_OuputStep->SetState(CATDlgUncheck);
	}
	if(CComFun::gbOutputPmi)
		_OutputPmi->SetState(CATDlgCheck);
	else
		_OutputPmi->SetState(CATDlgUncheck);

	if(CComFun::gbFromGraph)
		_FromGraph->SetState(CATDlgCheck);
	else
		_FromGraph->SetState(CATDlgUncheck);

	//设置位置
	_ChordLabel->SetGridConstraints(0,0,1,1,CATGRID_LEFT);
	_ChordEditor->SetGridConstraints(0,1,2,2,CATGRID_LEFT);
	_OuputStep->SetGridConstraints(2,0,1,1,CATGRID_LEFT);
	_OutputPmi->SetGridConstraints(3,0,1,1,CATGRID_LEFT);
	_FromGraph->SetGridConstraints(4,0,1,1,CATGRID_LEFT);
	//设置回调函数
	AddAnalyseNotificationCB(this, 
		this->GetDiaOKNotification(), 
		(CATCommandMethod)&CDlgSetOptionCmd::ClickOK, 
		NULL);
	AddAnalyseNotificationCB(this, 
		this->GetDiaCANCELNotification(), 
		(CATCommandMethod)&CDlgSetOptionCmd::ClickCancel, 
		NULL);

	
	this->SetVisibility(CATDlgShow);


	
//
//TODO: Add the constructor code here
//
}

//-----------------------------------------------------------------------------
// CDlgSetOptionCmd : destructor
//-----------------------------------------------------------------------------

CDlgSetOptionCmd::~CDlgSetOptionCmd()
{
//
// TODO: Place code here.
//
}



void CDlgSetOptionCmd::ClickOK(CATCommand           * iSendingCommand, 
	CATNotification      * iSentNotification, 
	CATCommandClientData   iUsefulData)
{
	//从编辑器中获取参数
	float dChord=0.0;
	dChord=_ChordEditor->GetFloatValue();
	
	if(dChord>0)
		CComFun::gfChord=dChord;
	else if(dChord<0)
		CComFun::gfChord=fabs(dChord);

	
	if(_OuputStep->GetState()==CATDlgCheck)
		CComFun::gbOutputStep=TRUE;
	else
		CComFun::gbOutputStep=FALSE;

	if(_OutputPmi->GetState()==CATDlgCheck)
		CComFun::gbOutputPmi=TRUE;
	else
		CComFun::gbOutputPmi=FALSE;

	if(_FromGraph->GetState()==CATDlgCheck)
		CComFun::gbFromGraph=TRUE;
	else
		CComFun::gbFromGraph=FALSE;
		
	this->RequestDelayedDestruction();//需要结束这个命令；
}

void CDlgSetOptionCmd::ClickCancel(CATCommand           * iSendingCommand, 
	CATNotification      * iSentNotification, 
	CATCommandClientData   iUsefulData)
{
	this->RequestDelayedDestruction();//需要结束这个命令；
}
