//===================================================================
// COPYRIGHT HUSTCAD 2018/12/14
//===================================================================
// CTestCmd.cpp
// Header definition of class CTestCmd
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2018/12/14 Creation: Code generated by the 3DS wizard
//===================================================================
#include "CATApplicationFrame.h"
#include "CATDlgDialog.h"
#include "CATDlgLabel.h"
#include "CATDlgEditor.h"
#include "CATDlgCheckButton.h"
#include "CATDlgPushButton.h"

#include "CATCreateExternalObject.h" 
#include "CComFun.h"

#include "CTestCmd.h"


CATCreateClass(CTestCmd);
//-----------------------------------------------------------------------------
// CTestCmd : constructor
//-----------------------------------------------------------------------------
CTestCmd::CTestCmd():CATDlgDialog(CATApplicationFrame::GetFrame()->GetMainWindow(),
	"CDlgSetOptionCmdId", 
	CATDlgGridLayout | CATDlgWndOK )
{
	_OutputStep=new CATDlgPushButton(this,"output step");
	_OutputStep->SetGridConstraints(0,0,1,1,CATGRID_LEFT);

	AddAnalyseNotificationCB(this, 
		this->GetDiaOKNotification(), 
		(CATCommandMethod)&CTestCmd::ClickOK, 
		NULL);

	AddAnalyseNotificationCB(_OutputStep, 
		_OutputStep->GetPushBActivateNotification(), 
		(CATCommandMethod)&CTestCmd::ClickOputStep, 
		NULL);
	this->SetVisibility(CATDlgShow);
}

//-----------------------------------------------------------------------------
// CTestCmd : destructor
//-----------------------------------------------------------------------------

CTestCmd::~CTestCmd()
{
//
// TODO: Place code here.
//
}

void CTestCmd::ClickOK(CATCommand           * iSendingCommand, 
	CATNotification      * iSentNotification, 
	CATCommandClientData   iUsefulData)
{
	RequestDelayedDestruction();
}
//点了outputstep按钮
void CTestCmd::ClickOputStep(CATCommand           * iSendingCommand, 
	CATNotification      * iSentNotification, 
	CATCommandClientData   iUsefulData)
{
	//先导入文件，然后导出文件看看
	CATBaseUnknown *pInput;
	pInput=CComFun::ImportStepFile(_T("G:\\项目\\湖北\\701\\IPDE_20180926Send\\05DOME.step"));
	CATIPLMComponent_var spComp;
	spComp=pInput;
	//CComFun::ExportStep(spComp);
}