//===================================================================
// COPYRIGHT TY 2019/01/02
//===================================================================
// IPDEforCATIAAddin.cpp
// Header definition of class IPDEforCATIAAddin
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2019/01/02 Creation: Code generated by the 3DS wizard
//===================================================================

#include "IPDEforCATIAAddin.h"
#include "CATAfrCommandHeader.h"
#include "CATCreateWorkshop.h"

class CATCmdContainer;

CATImplementClass(IPDEforCATIAAddin,
	Implementation,
	CATBaseUnknown,
	CATnull );

//定义并实现接口，这个接口应该是catia在调用dll的时候会启动这个东东
#include "TIE_CATIAfrGeneralWksAddin.h"
TIE_CATIAfrGeneralWksAddin(IPDEforCATIAAddin);
//-----------------------------------------------------------------------------
// IPDEforCATIAAddin : constructor
//-----------------------------------------------------------------------------
IPDEforCATIAAddin::IPDEforCATIAAddin():CATBaseUnknown()
{
//
//TODO: Add the constructor code here
//
}

//-----------------------------------------------------------------------------
// IPDEforCATIAAddin : destructor
//-----------------------------------------------------------------------------

IPDEforCATIAAddin::~IPDEforCATIAAddin()
{
//
// TODO: Place code here.
//
}


//用于创建commandheader，所有的command都必须要有一个commandheader
void IPDEforCATIAAddin::CreateCommands()
{
	//创建一个savetointevuecommandHeader

	CATBaseUnknown *pUnknown=	CATAfrCommandHeader::CATCreateCommandHeader(
		"ImportIPDEHdr",  //命令的id，自己定义
		"IPDEforCATIAAddin",  //dll的名称
		"ImportIPDECmd", //command的类型 
		(void *)NULL, //传给command的参数
		"IPDEforCATIAHeader",// command对应的资源文件名称
		CATFrmAvailable);
	if(pUnknown==NULL)
		MessageBox(NULL,_T("Create Commmand error! "),_T("IPDEforCATIA"),MB_OK);

	


}

//在acitve bar中创建相应的button
CATCmdContainer * IPDEforCATIAAddin::CreateToolbars()
{
	NewAccess(CATCmdContainer, pIPDEforCATIATlb, IPDEforCATIATlb);

	NewAccess(CATCmdContainer, pFixedSection, AfrActionBarFixedSection);
	AddAccessChild(pFixedSection, pIPDEforCATIATlb);

	NewAccess(CATCmdStarter, pImportIPDEStr, ImportIPDEStr);
	SetAccessCommand(pImportIPDEStr, "ImportIPDEHdr");
	SetAccessChild(pIPDEforCATIATlb, pImportIPDEStr);




	CATBaseUnknown * pCommand;
	pCommand=CATAfrCommandHeader::CATGetCommandHeader("ImportIPDEHdr");
	if(pCommand==NULL)
		MessageBox(NULL,_T("Get Command Head error! "),_T("IPDEforCATIA"),MB_OK);
	return pFixedSection;
}
